/**
 * In-memory demo data store.
 * Used when MongoDB is unavailable to provide a complete demo experience.
 */
import { Types } from 'mongoose';

const DEMO_FARMER_ID = new Types.ObjectId('6571a1b2c3d4e5f6a7b8c9d0');
const DEMO_FARM_ID = new Types.ObjectId('6571a1b2c3d4e5f6a7b8c9d1');
const DEMO_SCAN_1_ID = new Types.ObjectId('6571a1b2c3d4e5f6a7b8c9d2');
const DEMO_SCAN_2_ID = new Types.ObjectId('6571a1b2c3d4e5f6a7b8c9d3');
const DEMO_SCAN_3_ID = new Types.ObjectId('6571a1b2c3d4e5f6a7b8c9d4');

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);

export const demoFarmer = {
  _id: DEMO_FARMER_ID,
  name: 'Add your farm details',
  email: '',
  phone: '',
  location: {
    state: '',
    district: '',
    village: '',
  },
  language: 'en' as const,
  createdAt: new Date('2026-01-15T08:00:00Z'),
  updatedAt: new Date('2026-08-30T10:00:00Z'),
};

export const demoFarm = {
  _id: DEMO_FARM_ID,
  farmerId: DEMO_FARMER_ID,
  farmerName: '',
  location: {
    state: 'Haryana',
    district: 'Karnal',
    village: 'Gharaunda',
  },
  crop: 'Tomato',
  cropVariety: 'Pusa Ruby',
  farmArea: 2.5,
  farmAreaUnit: 'acres',
  plantingDate: daysAgo(47),
  cropAge: 47,
  growthStage: 'flowering' as const,
  irrigationMethod: 'drip' as const,
  soilType: 'loamy',
  previousDiseases: ['Tomato Leaf Spot'],
  previousTreatments: ['Neem oil spray', 'Copper fungicide'],
  notes: 'Regular monitoring schedule every 5 days.',
  createdAt: daysAgo(47),
  updatedAt: now,
};

export const demoScans = [
  {
    _id: DEMO_SCAN_1_ID,
    farmerId: DEMO_FARMER_ID,
    farmId: DEMO_FARM_ID,
    crop: 'Tomato',
    imageUrl: '/demo/scan1.jpg',
    disease: 'Tomato Leaf Spot',
    confidence: 0.91,
    severity: 22,
    affectedArea: 18,
    riskLevel: 'MODERATE',
    explanation: 'Small circular spots with dark margins visible on lower leaves, consistent with Septoria Leaf Spot. Disease is in early stages.',
    recommendations: [
      'Remove affected lower leaves',
      'Apply neem oil spray',
      'Improve air circulation',
    ],
    treatment: {
      immediate: ['Remove and destroy affected leaves immediately'],
      organic: ['Apply neem oil spray every 7 days', 'Use compost tea as foliar spray'],
      chemical: ['Consult local agricultural extension for approved fungicide options'],
      prevention: ['Maintain proper plant spacing', 'Use mulch around plants', 'Avoid overhead watering'],
      avoid: ['Do not compost diseased plant material', 'Avoid working with wet plants'],
    },
    weatherContext: {
      temperature: 32,
      humidity: 68,
      rainProbability: 20,
      conditions: 'Partly Cloudy',
    },
    isDemo: true,
    scanDate: daysAgo(14),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    _id: DEMO_SCAN_2_ID,
    farmerId: DEMO_FARMER_ID,
    farmId: DEMO_FARM_ID,
    crop: 'Tomato',
    imageUrl: '/demo/scan2.jpg',
    disease: 'Tomato Early Blight',
    confidence: 0.94,
    severity: 38,
    affectedArea: 32,
    riskLevel: 'HIGH',
    explanation: 'Concentric ring patterns on leaves consistent with Alternaria solani (Early Blight). Disease has progressed from previous scan. Immediate treatment recommended.',
    recommendations: [
      'Apply copper-based fungicide',
      'Remove severely affected leaves',
      'Improve drainage',
    ],
    treatment: {
      immediate: ['Apply copper-based organic fungicide immediately', 'Remove severely affected leaves'],
      organic: ['Neem oil spray', 'Baking soda solution (1 tbsp per gallon water)'],
      chemical: ['Consult local extension for approved fungicide — follow product label instructions'],
      prevention: ['Rotate crops next season', 'Improve soil drainage', 'Use disease-resistant varieties'],
      avoid: ['Avoid overhead watering', 'Do not work with plants when wet'],
    },
    weatherContext: {
      temperature: 30,
      humidity: 75,
      rainProbability: 45,
      conditions: 'Cloudy',
    },
    isDemo: true,
    scanDate: daysAgo(7),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    _id: DEMO_SCAN_3_ID,
    farmerId: DEMO_FARMER_ID,
    farmId: DEMO_FARM_ID,
    crop: 'Tomato',
    imageUrl: '/demo/scan3.jpg',
    disease: 'Tomato Early Blight',
    confidence: 0.95,
    severity: 18,
    affectedArea: 14,
    riskLevel: 'LOW',
    explanation: 'Treatment appears effective. Severity has decreased significantly from 38% to 18%. Some residual spots visible but new growth is healthy. Continue monitoring.',
    recommendations: [
      'Continue monitoring every 5 days',
      'Maintain treatment schedule',
      'Watch for new symptoms',
    ],
    treatment: {
      immediate: ['Continue current treatment protocol for one more week'],
      organic: ['Maintain neem oil spray schedule', 'Apply compost tea for plant health'],
      chemical: ['Continue as per previous recommendation if applied'],
      prevention: ['Keep monitoring weekly', 'Maintain good air circulation', 'Proper watering schedule'],
      avoid: ['Do not stop treatment prematurely', 'Avoid overwatering'],
    },
    weatherContext: {
      temperature: 31,
      humidity: 62,
      rainProbability: 15,
      conditions: 'Clear',
    },
    isDemo: true,
    scanDate: daysAgo(1),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

export const demoAlerts = [
  {
    _id: new Types.ObjectId(),
    farmerId: DEMO_FARMER_ID,
    type: 'disease_risk' as const,
    severity: 'warning' as const,
    title: '⚠️ Moderate Disease Risk',
    message: 'High humidity levels (75%) combined with recent rainfall increase the risk of fungal diseases. Monitor your tomato crop closely.',
    titleHi: '⚠️ मध्यम रोग जोखिम',
    messageHi: 'उच्च आर्द्रता (75%) और हाल की बारिश से कवक रोगों का खतरा बढ़ गया है। अपनी टमाटर की फसल पर नज़र रखें।',
    isRead: false,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    _id: new Types.ObjectId(),
    farmerId: DEMO_FARMER_ID,
    type: 'treatment_window' as const,
    severity: 'info' as const,
    title: '⏰ Treatment Window Available',
    message: 'Favorable conditions expected tomorrow evening (5:00 PM - 7:00 PM). Low rain probability and moderate winds — suitable for treatment application.',
    titleHi: '⏰ उपचार का समय उपलब्ध',
    messageHi: 'कल शाम (5:00 PM - 7:00 PM) अनुकूल स्थितियाँ अपेक्षित हैं। कम बारिश की संभावना और मध्यम हवा — उपचार के लिए उपयुक्त।',
    isRead: false,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: new Types.ObjectId(),
    farmerId: DEMO_FARMER_ID,
    type: 'follow_up' as const,
    severity: 'info' as const,
    title: '📷 Follow-up Scan Recommended',
    message: 'It has been 5 days since your last treatment. Upload a new crop image to monitor recovery and track disease progression.',
    titleHi: '📷 फॉलो-अप स्कैन अनुशंसित',
    messageHi: 'आपके अंतिम उपचार के 5 दिन हो गए हैं। रिकवरी की निगरानी के लिए एक नई फसल छवि अपलोड करें।',
    isRead: false,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    _id: new Types.ObjectId(),
    farmerId: DEMO_FARMER_ID,
    type: 'regional_outbreak' as const,
    severity: 'critical' as const,
    title: '🚨 Regional Disease Alert',
    message: 'Early Blight activity detected in Haryana region with 8 reports in the last 2 weeks. Take preventive measures.',
    titleHi: '🚨 क्षेत्रीय रोग चेतावनी',
    messageHi: 'हरियाणा क्षेत्र में अर्ली ब्लाइट की गतिविधि पाई गई है, पिछले 2 सप्ताह में 8 रिपोर्ट। निवारक उपाय करें।',
    isRead: false,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: new Types.ObjectId(),
    farmerId: DEMO_FARMER_ID,
    type: 'weather_risk' as const,
    severity: 'warning' as const,
    title: '🌧️ Weather Warning',
    message: 'Heavy rainfall expected in the next 48 hours. Ensure proper drainage and postpone any planned pesticide application.',
    titleHi: '🌧️ मौसम चेतावनी',
    messageHi: 'अगले 48 घंटों में भारी बारिश की संभावना है। उचित जल निकासी सुनिश्चित करें और किसी भी नियोजित कीटनाशक आवेदन को स्थगित करें।',
    isRead: false,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
];

export const demoRegionalReports = [
  {
    _id: new Types.ObjectId(),
    region: 'Karnal, Haryana',
    state: 'Haryana',
    district: 'Karnal',
    disease: 'Tomato Early Blight',
    reportCount: 8,
    severity: 'HIGH',
    coordinates: { lat: 29.6857, lng: 76.9905 },
    isDemo: true,
    reportDate: daysAgo(3),
    createdAt: daysAgo(3),
  },
  {
    _id: new Types.ObjectId(),
    region: 'Ludhiana, Punjab',
    state: 'Punjab',
    district: 'Ludhiana',
    disease: 'Leaf Spot',
    reportCount: 5,
    severity: 'MODERATE',
    coordinates: { lat: 30.9010, lng: 75.8573 },
    isDemo: true,
    reportDate: daysAgo(5),
    createdAt: daysAgo(5),
  },
  {
    _id: new Types.ObjectId(),
    region: 'Sonipat, Haryana',
    state: 'Haryana',
    district: 'Sonipat',
    disease: 'Powdery Mildew',
    reportCount: 3,
    severity: 'MODERATE',
    coordinates: { lat: 28.9931, lng: 77.0151 },
    isDemo: true,
    reportDate: daysAgo(7),
    createdAt: daysAgo(7),
  },
  {
    _id: new Types.ObjectId(),
    region: 'Jaipur, Rajasthan',
    state: 'Rajasthan',
    district: 'Jaipur',
    disease: 'Bacterial Spot',
    reportCount: 4,
    severity: 'HIGH',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    isDemo: true,
    reportDate: daysAgo(4),
    createdAt: daysAgo(4),
  },
  {
    _id: new Types.ObjectId(),
    region: 'Meerut, Uttar Pradesh',
    state: 'Uttar Pradesh',
    district: 'Meerut',
    disease: 'Late Blight',
    reportCount: 6,
    severity: 'HIGH',
    coordinates: { lat: 28.9845, lng: 77.7064 },
    isDemo: true,
    reportDate: daysAgo(2),
    createdAt: daysAgo(2),
  },
  {
    _id: new Types.ObjectId(),
    region: 'Nashik, Maharashtra',
    state: 'Maharashtra',
    district: 'Nashik',
    disease: 'Tomato Yellow Leaf Curl',
    reportCount: 7,
    severity: 'HIGH',
    coordinates: { lat: 19.9975, lng: 73.7898 },
    isDemo: true,
    reportDate: daysAgo(6),
    createdAt: daysAgo(6),
  },
];

export const demoWeather = {
  current: {
    temperature: 31,
    feelsLike: 34,
    humidity: 68,
    windSpeed: 12,
    windDirection: 'SW',
    conditions: 'Partly Cloudy',
    icon: '02d',
    rainProbability: 25,
    uvIndex: 7,
    pressure: 1008,
    visibility: 8,
  },
  forecast: [
    {
      date: new Date(now.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      dayName: 'Tomorrow',
      high: 33,
      low: 24,
      humidity: 72,
      rainProbability: 40,
      conditions: 'Cloudy',
      icon: '04d',
      windSpeed: 15,
    },
    {
      date: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      dayName: getDayName(2),
      high: 30,
      low: 23,
      humidity: 82,
      rainProbability: 70,
      conditions: 'Rain Expected',
      icon: '10d',
      windSpeed: 18,
    },
    {
      date: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      dayName: getDayName(3),
      high: 28,
      low: 22,
      humidity: 85,
      rainProbability: 80,
      conditions: 'Heavy Rain',
      icon: '09d',
      windSpeed: 22,
    },
    {
      date: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      dayName: getDayName(4),
      high: 31,
      low: 23,
      humidity: 70,
      rainProbability: 30,
      conditions: 'Partly Cloudy',
      icon: '02d',
      windSpeed: 10,
    },
    {
      date: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      dayName: getDayName(5),
      high: 33,
      low: 24,
      humidity: 60,
      rainProbability: 10,
      conditions: 'Clear',
      icon: '01d',
      windSpeed: 8,
    },
  ],
  weatherRisk: {
    level: 'MODERATE' as const,
    score: 55,
    reasoning: 'High humidity (68%) and expected rainfall in the next 48 hours may increase fungal disease risk. The warm temperatures (31°C) combined with moisture create favorable conditions for Early Blight and other fungal pathogens.',
    reasoningHi: 'उच्च आर्द्रता (68%) और अगले 48 घंटों में अपेक्षित बारिश से कवक रोग का खतरा बढ़ सकता है। गर्म तापमान (31°C) के साथ नमी अर्ली ब्लाइट और अन्य कवक रोगजनकों के लिए अनुकूल परिस्थितियाँ बनाती है।',
  },
  isDemo: true,
};

function getDayName(daysFromNow: number): string {
  const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const date = new Date(now.getTime() + daysFromNow * 24 * 60 * 60 * 1000);
  return days[date.getDay()];
}

export const DEMO_IDS = {
  farmerId: DEMO_FARMER_ID,
  farmId: DEMO_FARM_ID,
  scanIds: [DEMO_SCAN_1_ID, DEMO_SCAN_2_ID, DEMO_SCAN_3_ID],
};
